### ISSUE TITLE
Different site 

### ISSUE THREAD

**Issue by purpurato** [coinables/segwitaddress#10]
Hi, 
I was looking for your website and I found there are actually two of them, so I think one is a malicious. I guess some people might be harmed by this and you could maybe verify and report. Not sure how to proceed, so I rather let you know. 

![Screenshot from 2019-04-08 17-07-54](https://user-images.githubusercontent.com/38221405/55760146-e80b0380-5a20-11e9-91a2-c6c4e843c3a8.png)

**Comment by coinables** [comment]
Yes the one with only one "d" in the word address is a fake and malicious.
It WILL steal your funds.  I have reported to Google, that's all we can do
until they de-list it.
