### ISSUE TITLE
Address generation

### ISSUE THREAD

**Issue by rafaelpac** [coinables/segwitaddress#11]
Hi!
I don't understand something.
If I take private key
`0000000000000000000000000000000000000000000000000000000000000001`
private key WIF is
`KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3qYjgd9M7rFU73sVHnoWn`
public key compressed is
`0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798`

https://segwitaddress.org/ will give me address
`3JvL6Ymt8MVWiCNHC7oWU6nLeHNJKLZGLN`
but BTCPY will give me
`3CNHUhP3uyB9EUtRLsmvFUmvGdjGdkTxJw`

https://segwitaddress.org/bech32/  will give me address
`bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4`
but BTCPY will give me
`bc1qw508d6qejxtdg4y5r3zarvary0c5xw7kv8f3t4  (version 0)`
`bc1pw508d6qejxtdg4y5r3zarvary0c5xw7k8e76x7  (version 1)`
`bc1zw508d6qejxtdg4y5r3zarvary0c5xw7k6jw83r  (version 2)`

Why are these differences?

**Comment by coinables** [comment]
What is BTCPY?
Also are you referring to the brain wallet feature?

**Comment by rafaelpac** [comment]
Hi, sorry, I forgot to mention. BTCPy is a Python library for dealing with BTC.
https://github.com/chainside/btcpy

I am aware that the differences come from the script used, I have been reading about it, but I couldn't figure it out yet.

**Comment by coinables** [comment]
This appears to be an issue with btcpy

https://github.com/chainside/btcpy/issues/27
https://github.com/chainside/btcpy/issues/40
