### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by ctrlcctrlv** [coinables/segwitaddress#15]
Please.

**Comment by coinables** [comment]
https://github.com/coinables/segwitaddress/commit/e2007930bc6373f9907cbd5d3811e51bc5fb4677

**Comment by ctrlcctrlv** [comment]
Thanks! Updated [ctrlcctrlv/tripkeys: `doc/OVERVIEW.md`](https://github.com/ctrlcctrlv/tripkeys/blob/3a795bc27138f2819cd9485a32dd620d2b0bed73/doc/OVERVIEW.md#non-technical-anonymous-user-flow).
