### ISSUE TITLE
Is there PGP for this?

### ISSUE THREAD

**Issue by AlftheElf** [coinables/segwitaddress#17]
I may be missing it, but if not, would it be a good idea to add some PGP so we can be sure nothing has been tampered with? 🦄

**Comment by coinables** [comment]
It's GPG. See the "verified" flag on commit signature under releases 
https://github.com/coinables/segwitaddress/releases
https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/managing-commit-signature-verification
