### ISSUE TITLE
safari, can't load bech32/index.html directly

### ISSUE THREAD

**Issue by petjal** [coinables/segwitaddress#21]
In safari on macos, when running offline, in a private browser window, when I try to load 
file:///github/coinables/segwitaddress/bech32/index.html
clicking the blue `Generate New SegWit Address` button just scrolls the page a little bit.
But if first open file:///github/coinables/segwitaddress/index.html it works fine.
I don't have to do that in chrome on my chromebook. 
Sorry, I'm weak on macos, having trouble downloading/installing chrome and firefox on my son's old hand-me-down air.

**Comment by petjal** [comment]
While I did see this several times, I'm having trouble reproducing this at the moment, sorry.

**Comment by petjal** [comment]
Opening bech32/index.html directly works fine on Chrome and Firefox.

**Comment by coinables** [comment]
Corrected with latest updates and commits. https://github.com/coinables/segwitaddress/commit/14d61616e5cb70a920b4358660a58c75fc6449bd#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051
