### ISSUE TITLE
Block space

### ISSUE THREAD

**Issue by bom64** [coinables/segwitaddress#3]
SegWit is also about more tx per block. And it is needed. Mempool have being full 42 days. 
https://jochen-hoenicke.de/queue/#3m

But some SegWit implementation use more byte per block:

https://btcmanager.com/electrum-3-0-first-wallet-enable-bech32-segwit-addresses

Do the current implementation use more or less bytes?

If more byte:
Why not use bech32?

**Comment by coinables** [comment]
I have a bech32 version, but haven't pushed it to master yet. Debating if I
should let users decide between p2sh and bech32, or just do bech32 only.
Thank you for your input and contributing.

**Comment by coinables** [comment]
#4 https://github.com/coinables/segwitaddress/issues/4
