### ISSUE TITLE
cant accept bc1 wallet address

### ISSUE THREAD

**Issue by kolet** [coinables/segwitaddress#4]
hey,
i have tried to see if its possible to send the funds to a bc1 wallet, and it cant.

**Comment by coinables** [comment]
Currently the creation of bech32 addresses is a hidden feature only. Enter `bech32()` in your browser developer console this will generate a random bech32 key pair and QR codes. The sweep feature currently does not support bech32 addresses, so make sure you know how to import bech32 keys to another wallet such as bitcoin core client, electrum, samurai.
