### ISSUE TITLE
Bulk generated addresses don't work. Is it a scam?

### ISSUE THREAD

**Issue by anibal58** [coinables/segwitaddress#6]
Only that, do you have an email to contact you, please?

**Comment by coinables** [comment]
Can you explain what you mean by "don't work"? What happened, and what have you tried so far?
No it's not a scam.

**Comment by anibal58** [comment]
Hi, I have generated many addresses, used one and sent BTC. Now I try to spend that BTC using blockchain.info and the error message says that the primary key does not match with the address I used.
The format is:
1, "Address", "Primary key"
Right?

**Comment by coinables** [comment]
Ok, private keys are indistinguishable between segwit and legacy addresses. Blockchain.info is not compatible with importing segwit private keys, so the address you are seeing on blockchain.info is the legacy address that corresponds to the private key. You can use the sweep feature built into segwitaddress.org or use a wallet that supports segwit private key sweeping such as Samurai.

**Comment by anibal58** [comment]
Oh, I understand, I'll check that later. Thank you.
I'm sorry for calling your site a scam.
