### ISSUE TITLE
Can this be modified to work with Extended Wallet

### ISSUE THREAD

**Issue by juliustip** [coinables/segwitaddress#8]
I want to know if there is a way to bulk generate address of an extended wallet.
i.e. A user enters an xPub or xPriv Key, and can then generate as many address under such.
This will make it easy to keep just the Xpub and Xpriv for fund sweeping.

**Comment by EAWF** [comment]
From what I've been able to learn, you would want to create a payment address from the hardened account-level xPub key.
You may want to take a look at, or participate in the project located at: https://github.com/EAWF/BTCJS4Merchants that may be an answer to your question.

**Comment by coinables** [comment]
Currently no, but I like the suggestion as a feature. Sweeping an xprv would be pretty neat. 

Some tools to reference:
https://en.bitcoin.it/wiki/Deterministic_wallet_tools
