### ISSUE TITLE
Contribution offer.

### ISSUE THREAD

**Issue by designsats** [coinables/segwitaddress#9]
Hello,
thank you for this great tool. Are you open for community contributions? I am a graphic designer and front-end dev and I would like to improve the UI and usability of this project. 

Some of my references: 
https://dribbble.com/AndrejCibik
https://steemit.com/@andrejcibik

Andrej Cibík

**Comment by coinables** [comment]
Yes absolutely, please contribute if you can. Yes UI and UX can be changed, but please do not use CDNs or calls to outside resources, it is important that it can be easily run offline.
